backend:
  name: github
  repo: cafecommapa/cafecommapa
  branch: main

media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "summary", widget: "string"}
      - {label: "Cidade", name: "city", widget: "string"}
      - {label: "País", name: "country", widget: "string"}
      - {label: "Categoria", name: "category", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Imagem", name: "cover", widget: "image"}
      - {label: "Destaque", name: "featured", widget: "boolean"}
      - {label: "Mostrar no mapa", name: "show_on_map", widget: "boolean"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
